name: MCEngineBackPack
version: ${version}
main: io.github.mcengine.MCEngineBackPack
author: MCEngine
description: MCEngine BackPack
api-version: 1.18
softdepend: [HeadDatabaseAPI]
commands:
  givebackpack:
    description: Gives a player a backpack.
    usage: /givebackpack <head id> <size>